---
apiVersion: v1
kind: Secret
metadata:
  name: secret-key
data:
  secretkey: bGtzZGY5OHdyaGtqczg4ZHNmOC0zMjRrc2RtCg==
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todoapp
  labels:
    name: todoapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: todoapp
    spec:
      containers:
      - name: guestbook
        image: todoapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-passwords
                key: djangouserpw
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: secret-key
                key: secretkey
          - name: DB_HOST
            value: postgres
          - name: DB_USER
            value: todo
          - name: DB_NAME
            value: todo

---

apiVersion: v1
kind: Service
metadata:
  name: todoapp
  labels:
    name: todoapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    name: todoapp
